version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Asia/Tokyo"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        group-by: "dependency-name"
