/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JudgesIndexRouteImport } from './routes/judges/index'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as JudgesJudgeIdRouteImport } from './routes/judges/$judgeId'
import { Route as CasesCaseIdRouteImport } from './routes/cases/$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesIndexRoute = JudgesIndexRouteImport.update({
  id: '/judges/',
  path: '/judges/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesJudgeIdRoute = JudgesJudgeIdRouteImport.update({
  id: '/judges/$judgeId',
  path: '/judges/$judgeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/cases/': typeof CasesIndexRoute
  '/judges/': typeof JudgesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/cases': typeof CasesIndexRoute
  '/judges': typeof JudgesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/judges/$judgeId': typeof JudgesJudgeIdRoute
  '/cases/': typeof CasesIndexRoute
  '/judges/': typeof JudgesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases/$caseId'
    | '/judges/$judgeId'
    | '/cases/'
    | '/judges/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases/$caseId' | '/judges/$judgeId' | '/cases' | '/judges'
  id:
    | '__root__'
    | '/'
    | '/cases/$caseId'
    | '/judges/$judgeId'
    | '/cases/'
    | '/judges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  JudgesJudgeIdRoute: typeof JudgesJudgeIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  JudgesIndexRoute: typeof JudgesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/': {
      id: '/judges/'
      path: '/judges'
      fullPath: '/judges/'
      preLoaderRoute: typeof JudgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges/$judgeId': {
      id: '/judges/$judgeId'
      path: '/judges/$judgeId'
      fullPath: '/judges/$judgeId'
      preLoaderRoute: typeof JudgesJudgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  JudgesJudgeIdRoute: JudgesJudgeIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  JudgesIndexRoute: JudgesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
