name: Deploy Cloudflare Extract Worker

on:
  push:
    branches:
      - main
    paths:
      - app/extract/**
      - packages/**
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/cf-worker-deploy.yaml
    with:
      worker: extract
    secrets: inherit
